### ISSUE TITLE
can´t generate QR code

### ISSUE THREAD

**Issue by Tsamsiyu1** [raweee/node-red-contrib-whatsapp-link#6]
hi its me again^^
i try and try but i can´t generate a QR code.
in nodered it stays on Connecting...
and in the terminal it says this:

```
0|node-red`  | TypeError: Cannot read properties of null (reading 'close')
0|node-red  |     at Client.destroy (/home/marcel/.node-red/node_modules/whatsapp-web.js/src/Client.js:569:31)
0|node-red  |     at WhatsappAdmin.WARestart (/home/marcel/.node-red/node_modules/node-red-contrib-whatsapp-link/whatsappLink.js:100:26)
0|node-red  |     at WhatsappAdmin._inputCallback (/home/marcel/.node-red/node_modules/node-red-contrib-whatsapp-link/admin.js:33:22)
0|node-red  |     at /home/marcel/.nvm/versions/node/v17.6.0/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
0|node-red  |     at Object.trigger (/home/marcel/.nvm/versions/node/v17.6.0/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
0|node-red  |     at WhatsappAdmin.Node._emitInput (/home/marcel/.nvm/versions/node/v17.6.0/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
0|node-red  |     at WhatsappAdmin.Node.emit (/home/marcel/.nvm/versions/node/v17.6.0/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
0|node-red  |     at WhatsappAdmin.Node.receive (/home/marcel/.nvm/versions/node/v17.6.0/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
0|node-red  |     at Immediate.<anonymous> (/home/marcel/.nvm/versions/node/v17.6.0/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
0|node-red  |     at processImmediate (node:internal/timers:466:21)
0|node-red  | 10 Jan 17:11:01 - [info] [whatsappLink:Web] Error : Connection is slow...
0|node-red  | 10 Jan 17:11:11 - [info] [whatsappLink:Web] Error : Connection is slow...
```

I´m just sending the string restart in msg.payload.

**Comment by raweee** [comment]
Can not read property of null, means Whatsapp Client is not even initialise yet (client is null). Try to restart complete flow or complete node-red once if possible.

Till I'll see what change require in code to solve the problem.

**Comment by Tsamsiyu1** [comment]
this is right after a restart of node red.
I can´t initialize a whatsapp client at all.

**Comment by raweee** [comment]
Hi,
Simply restart of node-red will work, that problem was occur due to delay in connecting with whatsapp. Please wait after restart (at QR stage).

Using `restart` command multiple time crashes the whatsapp-node. It is fixed but not perfectly :smile:  working on it :+1:

**Comment by Tsamsiyu1** [comment]
ok i will try this now

**Comment by Tsamsiyu1** [comment]
Ok this is still not working but i get an other error now.

` Error: Failed to launch the browser process!
0|node-red  | /home/marcel/.node-red/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
0|node-red  | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
0|node-red  |     at onClose (/home/marcel/.node-red/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)
0|node-red  |     at Interface.<anonymous> (/home/marcel/.node-red/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)
0|node-red  |     at Interface.emit (node:events:539:35)
0|node-red  |     at Interface.emit (node:domain:475:12)
0|node-red  |     at Interface.close (node:internal/readline/interface:529:10)
0|node-red  |     at Socket.onend (node:internal/readline/interface:258:10)
0|node-red  |     at Socket.emit (node:events:539:35)
0|node-red  |     at Socket.emit (node:domain:475:12)
0|node-red  |     at endReadableNT (node:internal/streams/readable:1342:12)
0|node-red  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)
`

this means i need pupeteer if i read this correct.
will try this now

**Comment by Tsamsiyu1** [comment]
ok this does nothing. i checkt and i don't have a hidden directory called .node-red. within /home/user/
i have the node_dules directory right in there.
so no 
/home/marcel/.node-red/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome
but i have
/home/marcel/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome
